#!/usr/bin/env python

import sys

from tuw_iwos_revolute_and_steering_plugin.tuw_iwos_revolute_and_steering_plugin import RevoluteAndSteeringPlugin
from rqt_gui.main import Main

plugin = 'RevoluteAndSteeringPlugin'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
