robot_hardware:
#  - tuw_trinamic_ros_control_interface
  - tuw_dynamixel_ros_control_interface

#tuw_trinamic_ros_control_interface:
#  type: tuw_trinamic_ros_control/TrinamicControlInterface
#  joints:
#    - left_revolute
#    - right_revolute

tuw_dynamixel_ros_control_interface:
  type: tuw_dynamixel_ros_control/RobotHardwareInterface
  joints:
    - left_steering
    - right_steering
