controller:
  # STATE CONTROLLER / STATE PUBLISHER
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 300

  # POSITION CONTROLLER
  position_controller_left:
    type: position_controllers/JointPositionController
    joint: left_steering

  position_controller_right:
    type: position_controllers/JointPositionController
    joint: right_steering

  # EFFORT CONTROLLER
  effort_controller_left:
    type: effort_controllers/JointPositionController
    joint: left_steering
    pid: {p: 100.0, i: 1.0, d: 1.0}

  effort_controller_right:
    type: effort_controllers/JointPositionController
    joint: left_steering
    pid: {p: 100.0, i: 1.0, d: 1.0}