revolute:
  hardware_interface:
    joints:
      - left_revolute
      - right_revolute

steering:
  hardware_interface:
    joints:
      - left_steering
      - right_steering

controller:
  # STATE CONTROLLER / STATE PUBLISHER
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 10

  # REVOLUTE CONTROLLER
  left_revolute_controller:
    type: velocity_controllers/JointVelocityController
    joint: left_revolute

  right_revolute_controller:
    type: velocity_controllers/JointVelocityController
    joint: right_revolute

  # STEERING CONTROLLER
  left_steering_controller:
    type: position_controllers/JointPositionController
    joint: left_steering

  right_steering_controller:
    type: position_controllers/JointPositionController
    joint: right_steering
