#!/usr/bin/env python

import sys

from tuw_iwos_rqt_control.tuw_iwos_rqt_control import IWOSControl
from rqt_gui.main import Main

plugin = 'IWOS_Control'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))