setup: trinamic
joints:
  - name: "left_revolute"
    id: 0
    connection: { port: "/dev/ttyACM0", baudrate: 9600 }
    hardware:   { package: "tuw_iwos_hardware", path: "resources/hardware/revolute/trinamic_TMCM-1640.yaml" }
    config:     { package: "tuw_iwos_hardware", path: "resources/config/revolute/trinamic_TMCM-1640.yaml" }
  - name: "right_revolute"
    id: 0
    connection: { port: "/dev/ttyACM1", baudrate: 9600 }
    hardware:   { package: "tuw_iwos_hardware", path: "resources/hardware/revolute/trinamic_TMCM-1640.yaml" }
    config:     { package: "tuw_iwos_hardware", path: "resources/config/revolute/trinamic_TMCM-1640.yaml" }
