config:
  - identifier: motor_poles
    value: 20
  - identifier: regulation_loop_delay
    value: 1
  - identifier: overvoltage_protection
    value: 0
  - identifier: driver_switch
    value: 1
  - identifier: ramp_switch
    value: 0
  - identifier: communication_mode
    value: 0
  - identifier: target_reached_distance
    value: 5
  - identifier: target_reached_velocity
    value: 5
  - identifier: motor_halted_velocity
    value: 5
  - identifier: maximum_current
    value: 3000
  - identifier: position_p_parameter
    value: 0
  - identifier: velocity_p_parameter
    value: 2000
  - identifier: velocity_i_parameter
    value: 100
  - identifier: current_p_parameter
    value: 1500
  - identifier: current_i_parameter
    value: 300
  - identifier: init_sine_mode
    value: 1
