motor_poles:            10
overvoltage_protection:  0
driver_switch:           1
ramp_switch:             0
communication_mode:      8
target_reached_distance: 5
target_reached_velocity: 5
motor_halted_velocity:   5
maximum_current:      1000
position_p_parameter:    0
velocity_p_parameter: 1000
velocity_i_parameter:  500
current_p_parameter:   100
current_i_parameter:   100
