revolute:
  hardware_interface:
    joints:
      - revolute_left
      - revolute_right

steering:
  hardware_interface:
    joints:
      - steering_left
      - steering_right

controller:
  # STATE CONTROLLER / STATE PUBLISHER
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 60

  # REVOLUTE CONTROLLER
  revolute_left_controller:
    type: velocity_controllers/JointVelocityController
    joint: revolute_left

  revolute_right_controller:
    type: velocity_controllers/JointVelocityController
    joint: revolute_right

  # STEERING CONTROLLER
  steering_left_controller:
    type: position_controllers/JointPositionController
    joint: steering_left

  steering_right_controller:
    type: position_controllers/JointPositionController
    joint: steering_right
