#!/usr/bin/env python

import sys

from tuw_iwos_control_plugin.tuw_iwos_control_plugin import ControlPlugin
from rqt_gui.main import Main

plugin = 'IWOS Control Plugin'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))