IWOS:

  # REVOLUTE
  revolute:
    hardware_interface:
      joints:
        - left_revolute
        - right_revolute

  # STEERING
  steering:
    hardware_interface:
      joints:
        - left_steering
        - right_steering

  controller:

    # REVOLUTE
    revolute_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 300

    revolute_velocity_controller_left:
      type: velocity_controllers/JointVelocityController
      joint: left_revolute

    revolute_velocity_controller_right:
      type: velocity_controllers/JointVelocityController
      joint: right_revolute

    # STEERING
    steering_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 300

    steering_position_controller_left:
      type: position_controllers/JointPositionController
      joint: left_steering

    steering_position_controller_right:
      type: position_controllers/JointPositionController
      joint: left_steering
