geometry_msgs/PoseStamped pose_start
std_msgs/Float64 pose_orientation_offset_start
geometry_msgs/PoseStamped pose_end
std_msgs/Float64 pose_orientation_offset_end

geometry_msgs/PoseStamped odometry_start
std_msgs/Float64 odometry_orientation_offset_start

std_msgs/Float64[] alpha_values

---

geometry_msgs/PoseStamped odometry_end
std_msgs/Float64 odometry_orientation_offset_end
